// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbE9RDY4wzJCIcY7P92N1FYqfJPcr7k1k',
    appId: '1:332546023963:web:da19c31919170c7cdb0ebe',
    messagingSenderId: '332546023963',
    projectId: 'marathi-ai-15122023',
    authDomain: 'marathi-ai-15122023.firebaseapp.com',
    storageBucket: 'marathi-ai-15122023.appspot.com',
    measurementId: 'G-T4ET71F88C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6_kgO_9Con7Fv4oKVeVDBT6JV4v4BGSY',
    appId: '1:332546023963:android:5c2d765ce5dd610adb0ebe',
    messagingSenderId: '332546023963',
    projectId: 'marathi-ai-15122023',
    storageBucket: 'marathi-ai-15122023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC70qRayJ1Ffl5VXLmFggzZMzf63PWc_jc',
    appId: '1:332546023963:ios:8f4f724d7d6afea3db0ebe',
    messagingSenderId: '332546023963',
    projectId: 'marathi-ai-15122023',
    storageBucket: 'marathi-ai-15122023.appspot.com',
    iosBundleId: 'com.example.marathiAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC70qRayJ1Ffl5VXLmFggzZMzf63PWc_jc',
    appId: '1:332546023963:ios:a04621824013a884db0ebe',
    messagingSenderId: '332546023963',
    projectId: 'marathi-ai-15122023',
    storageBucket: 'marathi-ai-15122023.appspot.com',
    iosBundleId: 'com.example.marathiAi.RunnerTests',
  );
}
